# Generated by Django 2.2.5 on 2019-10-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_authuserextended'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUserExtend',
        ),
        migrations.DeleteModel(
            name='Usserimage',
        ),
    ]
